//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ntp.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.hocvienmang.com/", ConfigurationName="ServiceReference1.ExamForNtp01Soap")]
    public interface ExamForNtp01Soap {
        
        // CODEGEN: Generating message contract since element name UserName from namespace http://www.hocvienmang.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.hocvienmang.com/GetNtpMessage", ReplyAction="*")]
        Ntp.ServiceReference1.GetNtpMessageResponse GetNtpMessage(Ntp.ServiceReference1.GetNtpMessageRequest request);
        
        // CODEGEN: Generating message contract since element name UserName from namespace http://www.hocvienmang.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.hocvienmang.com/Submit", ReplyAction="*")]
        Ntp.ServiceReference1.SubmitResponse Submit(Ntp.ServiceReference1.SubmitRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetNtpMessageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetNtpMessage", Namespace="http://www.hocvienmang.com/", Order=0)]
        public Ntp.ServiceReference1.GetNtpMessageRequestBody Body;
        
        public GetNtpMessageRequest() {
        }
        
        public GetNtpMessageRequest(Ntp.ServiceReference1.GetNtpMessageRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.hocvienmang.com/")]
    public partial class GetNtpMessageRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string UserPass;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int ExamId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public long QuestionId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public long OriginateTimeUtcTick;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public byte[] ntpMesage;
        
        public GetNtpMessageRequestBody() {
        }
        
        public GetNtpMessageRequestBody(string UserName, string UserPass, int ExamId, long QuestionId, long OriginateTimeUtcTick, byte[] ntpMesage) {
            this.UserName = UserName;
            this.UserPass = UserPass;
            this.ExamId = ExamId;
            this.QuestionId = QuestionId;
            this.OriginateTimeUtcTick = OriginateTimeUtcTick;
            this.ntpMesage = ntpMesage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetNtpMessageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetNtpMessageResponse", Namespace="http://www.hocvienmang.com/", Order=0)]
        public Ntp.ServiceReference1.GetNtpMessageResponseBody Body;
        
        public GetNtpMessageResponse() {
        }
        
        public GetNtpMessageResponse(Ntp.ServiceReference1.GetNtpMessageResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.hocvienmang.com/")]
    public partial class GetNtpMessageResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetNtpMessageResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public long OriginateTimeUtcTick;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public byte[] ntpMesage;
        
        public GetNtpMessageResponseBody() {
        }
        
        public GetNtpMessageResponseBody(string GetNtpMessageResult, long OriginateTimeUtcTick, byte[] ntpMesage) {
            this.GetNtpMessageResult = GetNtpMessageResult;
            this.OriginateTimeUtcTick = OriginateTimeUtcTick;
            this.ntpMesage = ntpMesage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SubmitRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Submit", Namespace="http://www.hocvienmang.com/", Order=0)]
        public Ntp.ServiceReference1.SubmitRequestBody Body;
        
        public SubmitRequest() {
        }
        
        public SubmitRequest(Ntp.ServiceReference1.SubmitRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.hocvienmang.com/")]
    public partial class SubmitRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string UserPass;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int ExamId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public long QuestionId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public System.DateTime OriginateSendTimestamp;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public System.DateTime ReceiveTimestamp;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public System.DateTime TransmitTimestamp;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public System.DateTime OriginateReceiveTime;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public long DifferentTicks;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public System.DateTime DateTimeAfterSynchronize;
        
        public SubmitRequestBody() {
        }
        
        public SubmitRequestBody(string UserName, string UserPass, int ExamId, long QuestionId, System.DateTime OriginateSendTimestamp, System.DateTime ReceiveTimestamp, System.DateTime TransmitTimestamp, System.DateTime OriginateReceiveTime, long DifferentTicks, System.DateTime DateTimeAfterSynchronize) {
            this.UserName = UserName;
            this.UserPass = UserPass;
            this.ExamId = ExamId;
            this.QuestionId = QuestionId;
            this.OriginateSendTimestamp = OriginateSendTimestamp;
            this.ReceiveTimestamp = ReceiveTimestamp;
            this.TransmitTimestamp = TransmitTimestamp;
            this.OriginateReceiveTime = OriginateReceiveTime;
            this.DifferentTicks = DifferentTicks;
            this.DateTimeAfterSynchronize = DateTimeAfterSynchronize;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SubmitResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SubmitResponse", Namespace="http://www.hocvienmang.com/", Order=0)]
        public Ntp.ServiceReference1.SubmitResponseBody Body;
        
        public SubmitResponse() {
        }
        
        public SubmitResponse(Ntp.ServiceReference1.SubmitResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.hocvienmang.com/")]
    public partial class SubmitResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SubmitResult;
        
        public SubmitResponseBody() {
        }
        
        public SubmitResponseBody(string SubmitResult) {
            this.SubmitResult = SubmitResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ExamForNtp01SoapChannel : Ntp.ServiceReference1.ExamForNtp01Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ExamForNtp01SoapClient : System.ServiceModel.ClientBase<Ntp.ServiceReference1.ExamForNtp01Soap>, Ntp.ServiceReference1.ExamForNtp01Soap {
        
        public ExamForNtp01SoapClient() {
        }
        
        public ExamForNtp01SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ExamForNtp01SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExamForNtp01SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExamForNtp01SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Ntp.ServiceReference1.GetNtpMessageResponse Ntp.ServiceReference1.ExamForNtp01Soap.GetNtpMessage(Ntp.ServiceReference1.GetNtpMessageRequest request) {
            return base.Channel.GetNtpMessage(request);
        }
        
        public string GetNtpMessage(string UserName, string UserPass, int ExamId, long QuestionId, ref long OriginateTimeUtcTick, ref byte[] ntpMesage) {
            Ntp.ServiceReference1.GetNtpMessageRequest inValue = new Ntp.ServiceReference1.GetNtpMessageRequest();
            inValue.Body = new Ntp.ServiceReference1.GetNtpMessageRequestBody();
            inValue.Body.UserName = UserName;
            inValue.Body.UserPass = UserPass;
            inValue.Body.ExamId = ExamId;
            inValue.Body.QuestionId = QuestionId;
            inValue.Body.OriginateTimeUtcTick = OriginateTimeUtcTick;
            inValue.Body.ntpMesage = ntpMesage;
            Ntp.ServiceReference1.GetNtpMessageResponse retVal = ((Ntp.ServiceReference1.ExamForNtp01Soap)(this)).GetNtpMessage(inValue);
            OriginateTimeUtcTick = retVal.Body.OriginateTimeUtcTick;
            ntpMesage = retVal.Body.ntpMesage;
            return retVal.Body.GetNtpMessageResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Ntp.ServiceReference1.SubmitResponse Ntp.ServiceReference1.ExamForNtp01Soap.Submit(Ntp.ServiceReference1.SubmitRequest request) {
            return base.Channel.Submit(request);
        }
        
        public string Submit(string UserName, string UserPass, int ExamId, long QuestionId, System.DateTime OriginateSendTimestamp, System.DateTime ReceiveTimestamp, System.DateTime TransmitTimestamp, System.DateTime OriginateReceiveTime, long DifferentTicks, System.DateTime DateTimeAfterSynchronize) {
            Ntp.ServiceReference1.SubmitRequest inValue = new Ntp.ServiceReference1.SubmitRequest();
            inValue.Body = new Ntp.ServiceReference1.SubmitRequestBody();
            inValue.Body.UserName = UserName;
            inValue.Body.UserPass = UserPass;
            inValue.Body.ExamId = ExamId;
            inValue.Body.QuestionId = QuestionId;
            inValue.Body.OriginateSendTimestamp = OriginateSendTimestamp;
            inValue.Body.ReceiveTimestamp = ReceiveTimestamp;
            inValue.Body.TransmitTimestamp = TransmitTimestamp;
            inValue.Body.OriginateReceiveTime = OriginateReceiveTime;
            inValue.Body.DifferentTicks = DifferentTicks;
            inValue.Body.DateTimeAfterSynchronize = DateTimeAfterSynchronize;
            Ntp.ServiceReference1.SubmitResponse retVal = ((Ntp.ServiceReference1.ExamForNtp01Soap)(this)).Submit(inValue);
            return retVal.Body.SubmitResult;
        }
    }
}
